### ISSUE TITLE
cargo fmt; cargo clippy; compile for more boards; remove SPI RAM requirement; remove unused app & host code

### ISSUE THREAD

**Issue by ivmarkov** [georgik/rustzx-esp32#1]
JFYI - a PR with all of this is coming, when I have some free time.

**Comment by georgik** [comment]
Thank you.
Just check the latest main. I've added implementation which is using Rgb565 instead of RGBA.
The image should be correctly displayed on the screen.

**Comment by ivmarkov** [comment]
Good optimization. Yet:
* You can further optimize by allocating a buffer that keeps ZxColor instead of RGB565 instances. This way you'll go down from 16 bits per pixel to 4 bits per pixel and the need for SPI RAM will likely disappear
* Even further: I don't think this buffer that you guys have implemented is necessary. It is **never, ever read**, except at the end of the emulation, when you take it, create an image and blit the image onto the display. Instead of doing this, you can implement  the ZX emulator's FrameBuffer trait **directly on top of the embedded graphics display**, thus eradicating the buffer completely. This is what I'm working on actually.

**Comment by georgik** [comment]
BTW: Current frame-rate is 2 FPS. So definitely there is room for improvement. At least the emulator is able to display the screen.
ESP-IDF itself has support for DMA and color conversion which is not incorporated in the embedded-graphics.
There is similar project written using C, which has better performance: https://github.com/rampa069/ZX-ESPectrum
This can be good source of inspiration for improvements.

Right now this project has only video support, audio and keyboard handling is disabled now.

**Comment by ivmarkov** [comment]
> BTW: Current frame-rate is 2 FPS. So definitely there is room for improvement. At least the emulator is able to display the screen. ESP-IDF itself has support for DMA and color conversion which is not incorporated in the embedded-graphics. 

Indeed. To be seen how much can be achieved with pure software mode.

> There is similar project written using C, which has better performance: https://github.com/rampa069/ZX-ESPectrum This can be good source of inspiration for improvements.

Thanks.
 
> Right now this project has only video support, audio and keyboard handling is disabled now.

I saw that. Audio might be added via i2s (?). Keyboard - via BT (?). But video performance has to be improved first, of course. (If possible.)

**Comment by ivmarkov** [comment]
> > BTW: Current frame-rate is 2 FPS. So definitely there is room for improvement. At least the emulator is able to display the screen. ESP-IDF itself has support for DMA and color conversion which is not incorporated in the embedded-graphics.

Actually, embedded-graphics *can* indirectly use DMA, as long as the SPI driver underneath uses DMA (which `esp-idf-hal` doesn't do (yet), but it is very much possible).

As for color conversion - what do you mean?

**Comment by georgik** [comment]
Regarding color-space conversion: AFAIK ESP-IDF is able to translate Rgb888 image into the format supported by display e.g. Rgb565. 

In the case of ZX Spcetrum it should be even simpler, because there are just 16 colors. Here's mapping to Rgb565: https://github.com/georgik/rustzx-esp32/blob/main/src/app/video/palette.rs#L13
The original Rgba palette is here: https://github.com/pacmancoder/rustzx/blob/master/rustzx-utils/src/palette.rs#L2

**Comment by ivmarkov** [comment]
I think we are over-complicating the problem. Translating each of the 8 (or 16, with brightness) values to Rgb565 with a `match` statement is IMO good enough and fast enough. Again, I do not really understand why you guys were going with a large RGB888 buffer (or even a RGB565 buffer) in the first place, when you can use a small - ZX specific buffer, where for each ZX color you need just 4 bits (as opposed to 32 bits for RGBA or 16 for RGB565 which eats a lot of RAM).

**Comment by georgik** [comment]
PR merged. Thank you @ivmarkov for the contribution.
Let's close this issue. Further improvements can be moved to new issues.
